### ISSUE TITLE
ToC not displaying on iOS mobile

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2-docs#359]
when looking at iOS mobile, the docs ToC isn't appearing:
![Image](https://github.com/user-attachments/assets/21d3888c-40b9-409e-8c51-f50a7779185f)

**Comment by julioest** [comment]
This happens because of conflicting styles inside the `boostbookV2.css`. 

@daveoconnor We should also check these types of pages, similar to what we did for the learn docs. Here’s the example we're referencing: https://www.boost.io/doc/libs/develop/doc/antora/url/index.html

![Image](https://github.com/user-attachments/assets/8be4746a-7e28-4978-8e92-b12de72d0625)

**Comment by daveoconnor** [comment]
Talked to @julioest about this, and it seems to be working on staging as is, but we're going to make some changes anyway.

Active PR for this work is https://github.com/boostorg/website-v2/pull/1460
